name: Build and Deploy Dev Assets

on:
  push:
    branches:
      - dontuse

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting with Prettier
        run: npx prettier . --check

      - name: Build staging assets
        run: npm run build:staging

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to R2
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}

        run: |
          # Deploy staging assets (with --remote flag)
          wrangler r2 object put $R2_BUCKET_NAME/staging/manifest.json --file=dist/staging/manifest.json --remote
          find dist/staging/assets -type f -exec sh -c 'wrangler r2 object put $R2_BUCKET_NAME/staging/assets/$(basename "$1") --file="$1" --remote' _ {} \;
